// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLd0NxwwoLmq2VcEUg7Bbgn9-QD2Degbs',
    appId: '1:659382039460:web:014812ec2c7a9459488731',
    messagingSenderId: '659382039460',
    projectId: 'fir-app-d90fe',
    authDomain: 'fir-app-d90fe.firebaseapp.com',
    storageBucket: 'fir-app-d90fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw9eyUR9h32LFMHPio82_2KV-wkPqetz0',
    appId: '1:659382039460:android:680180c9e6053ae6488731',
    messagingSenderId: '659382039460',
    projectId: 'fir-app-d90fe',
    storageBucket: 'fir-app-d90fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADvVijer_BWlG4Tvgft3uKrGtQ1SX9us',
    appId: '1:659382039460:ios:fcffa00c3c567425488731',
    messagingSenderId: '659382039460',
    projectId: 'fir-app-d90fe',
    storageBucket: 'fir-app-d90fe.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAADvVijer_BWlG4Tvgft3uKrGtQ1SX9us',
    appId: '1:659382039460:ios:519f7323b23018f0488731',
    messagingSenderId: '659382039460',
    projectId: 'fir-app-d90fe',
    storageBucket: 'fir-app-d90fe.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
